import type { Metadata } from "next";
import { Kumbh_Sans } from "next/font/google";
import "./globals.css";
import { CartProvider } from "./ui/cart/cart-context";

const font = Kumbh_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Ecommerce Product Page",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <CartProvider>

        <body className={font.className}>{children}</body>
      </CartProvider>
    </html>
  );
}
